/**
 * Generates a deterministic HSL color from a string using a simple hash.
 * Used to map areaSolicitante → consistent color.
 */
function hashString(str: string): number {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i)
    hash = (hash << 5) - hash + char
    hash |= 0
  }
  return Math.abs(hash)
}

export function getAreaColor(areaSolicitante: string | null | undefined, fallbackCor?: string | null): string {
  if (fallbackCor) return fallbackCor

  if (!areaSolicitante) return '#6b7280' // gray-500 for unknown

  const h = hashString(areaSolicitante) % 360
  // Use fixed saturation/lightness for good readability on dark backgrounds
  return `hsl(${h}, 65%, 45%)`
}

export function getAreaTextColor(bgColor: string): string {
  // For HSL colors generated by getAreaColor, we always use white text
  // For custom hex colors, compute luminance
  if (bgColor.startsWith('hsl')) return '#ffffff'

  if (bgColor.startsWith('#') && bgColor.length === 7) {
    const r = parseInt(bgColor.slice(1, 3), 16) / 255
    const g = parseInt(bgColor.slice(3, 5), 16) / 255
    const b = parseInt(bgColor.slice(5, 7), 16) / 255
    const luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b
    return luminance > 0.5 ? '#111827' : '#ffffff'
  }

  return '#ffffff'
}
